categorieproduit_index:
    path:     /
    defaults: { _controller: "SoukFrontEndBundle:Categorieproduit:index" }
    methods:  GET

categorieproduit_show:
    path:     /{id}/show
    defaults: { _controller: "SoukFrontEndBundle:Categorieproduit:show" }
    methods:  GET

categorieproduit_new:
    path:     /new
    defaults: { _controller: "SoukFrontEndBundle:Categorieproduit:new" }
    methods:  [GET, POST]

categorieproduit_edit:
    path:     /{id}/edit
    defaults: { _controller: "SoukFrontEndBundle:Categorieproduit:edit" }
    methods:  [GET, POST]

categorieproduit_delete:
    path:     /{id}/delete
    defaults: { _controller: "SoukFrontEndBundle:Categorieproduit:delete" }
    methods:  DELETE
