reclamation_index:
    path:     /
    defaults: { _controller: "SoukFrontEndBundle:Reclamation:index" }
    methods:  GET

reclamation_show:
    path:     /{id}/show
    defaults: { _controller: "SoukFrontEndBundle:Reclamation:show" }
    methods:  GET

reclamation_new:
    path:     /new
    defaults: { _controller: "SoukFrontEndBundle:Reclamation:new" }
    methods:  [GET, POST]

reclamation_edit:
    path:     /{id}/edit
    defaults: { _controller: "SoukFrontEndBundle:Reclamation:edit" }
    methods:  [GET, POST]

reclamation_delete:
    path:     /{id}/delete
    defaults: { _controller: "SoukFrontEndBundle:Reclamation:delete" }


conditionsgenerale:
    path:     /reclamation/conditionsgenerale

reclamation_update:
    path:  /update/{id}
    defaults: { _controller: "SoukFrontEndBundle:Reclamation:update"}
    methods:  [GET, POST]
