reclamation_show:
    path:     /{id}/show
    defaults: { _controller: "SoukFrontEndBundle:Reclamation:show" }
    methods:  GET

reclamation_new:
    path:     /new
    defaults: { _controller: "SoukFrontEndBundle:Reclamation:new" }
    methods:  [GET, POST]

reclamation_edit:
    path:     /{id}/edit
    defaults: { _controller: "SoukFrontEndBundle:Reclamation:edit" }
    methods:  [GET, POST]

reclamation_delete:
    path:     /{id}/delete
    defaults: { _controller: "SoukFrontEndBundle:Reclamation:delete" }


conditionsgenerale:
    path:     /reclamation/conditionsgenerale
    defaults: { _controller: "SoukFrontEndBundle:Reclamation:conditions" }

reclamation_update:
    path:  /update/{id}
    defaults: { _controller: "SoukFrontEndBundle:Reclamation:update"}
    methods:  [GET, POST]

reclamation_detail:
    path:  /detail/{id}
    defaults: { _controller: "SoukFrontEndBundle:Reclamation:detail"}

quitter:
    path: /quitter
    defaults: { _controller: "SoukFrontEndBundle:Reclamation:quitter"}
