reclamation_backend_liste:
    path:     /
    defaults: { _controller: SoukBackEndBundle:Reclamation:reclamation_backend_liste }


reclamation_backend_supprime:
    path:     /supprimer
    defaults: { _controller: SoukBackEndBundle:Reclamation:reclamation_backend_supprimer }


reclamation_backend_statistique:
    path:     /stat
    defaults: { _controller: SoukBackEndBundle:Reclamation:reclamation_backend_stat }

