souk_front_end_boutique:
    resource: "@SoukFrontEndBundle/Resources/config/routing/boutique.yml"
    prefix:   /boutique


Souk_api_commande_liste:
    path:     /commande
    defaults: { _controller: SoukFrontEndBundle:Commande:Api_Commande_all }
Souk_api_commande_find:
    path:     /commande/{id}
    defaults: { _controller: SoukFrontEndBundle:Commande:Api_Commande_find }

Souk_api_categorie_produit_liste:
    path:     /produit/categorie
    defaults: { _controller: SoukFrontEndBundle:Categorieproduit:Api_Categorie_produit_all }
Souk_api_categorie_produit_find:
    path:     /produit/categorie/{id}
    defaults: { _controller: SoukFrontEndBundle:Categorieproduit:Api_Categorie_produit_find }
Souk_api_categorie_produit_new:
    path:     /produit/categorie/new
    defaults: { _controller: Categorieproduit:Api_Categorie_produit_new }




