parameters:

services:
#    souk_front_end.example:
#        class: Souk\FrontEndBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
    redirectionListener:
      class: Souk\FrontEndBundle\Listener\RedirectionListener
      arguments: ["@service_container","@session"]
      tags:
          - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }